import http from "node:http";
const PORT=Number(process.env.PORT||8787), AI_API_URL=process.env.AI_API_URL||"", AI_API_KEY=process.env.AI_API_KEY||"", AI_MODEL=process.env.AI_MODEL||"";
const PROFILES={"Midjourney":"Midjourney","Stable Diffusion":"Stable Diffusion","Ideogram":"image","Recraft":"design","Canva AI":"design","Canva Magic Studio":"design","Runway":"video","Google Veo":"video","Kling AI":"video","Pika":"video","Luma Dream Machine":"video","Hailuo AI":"video","Vidu":"video","LTX Studio":"video","ElevenLabs":"voice","PlayHT":"voice","Cartesia":"voice","Fish Audio":"voice","Murf":"voice","Speechify":"voice","Suno":"music","Udio":"music","Stable Audio":"music","Cursor":"coding","GitHub Copilot":"coding","Claude Code":"coding","Windsurf":"coding","Replit":"coding","Amazon Q Developer":"coding","Gemini Code Assist":"coding","Tabnine":"coding","Perplexity":"research","NotebookLM":"research","Elicit":"research","Consensus":"research","SciSpace":"research","Jasper":"marketing","Copy.ai":"marketing","Writesonic":"marketing","Grammarly":"writing","Writer":"writing","Gamma":"presentation","Beautiful.ai":"presentation","Tome":"presentation","Napkin AI":"presentation","Framer":"design","Meshy":"3d","Tripo AI":"3d"};
const RULES={"Midjourney":"Use Midjourney-native visual language: subject, environment, composition, camera/perspective, lighting, material, mood and aesthetic. Use --ar or --stylize only when justified. Never use Stable Diffusion negative-prompt syntax.","Stable Diffusion":"Use Stable Diffusion/SDXL structure: detailed positive prompt followed by a separate Negative Prompt. Use weighting syntax only when useful. Never add Midjourney flags.","video":"Write motion-first instructions: shot/framing, camera movement, subject action, environmental motion, timing/order, lighting, continuity and ending. Never describe impossible simultaneous actions.","voice":"Specify voice identity, age impression, tone, pace, rhythm, emotion, pronunciation and delivery. Do not import image/video syntax.","music":"Specify genre, mood, tempo, instrumentation, structure, vocal character and production. If lyrics are needed, separate lyrics from style direction.","coding":"Act as a senior engineer. Inspect requirements, assumptions, constraints and existing project structure before proposing changes. Produce actionable implementation guidance, tests and error handling. Never invent APIs.","research":"Use evidence-first research. Separate facts, inferences and opinions. Never invent citations. Flag uncertainty and date-stamp time-sensitive claims.","marketing":"Specify audience, offer, awareness stage, channel, core message, tone, CTA, constraints and measurable outputs.","writing":"Preserve author intent and voice unless change is requested. Specify audience, length, structure, tone and quality criteria.","presentation":"Design a presentation narrative: audience, objective, slide sequence, one key message per slide, visuals/data and speaker intent.","design":"Think like a production designer: deliverable, dimensions, grid/layout, hierarchy, typography, palette, components, spacing and final-use constraints.","3d":"Specify geometry, proportions, materials, surface detail, lighting, camera/view angle, background and intended use."};
const json=x=>JSON.stringify(x);
function send(res,code,obj){res.writeHead(code,{"Content-Type":"application/json","Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type"});res.end(json(obj));}
function body(req){return new Promise((resolve,reject)=>{let s="";req.on("data",c=>{s+=c;if(s.length>1200000)reject(new Error("body_too_large"));});req.on("end",()=>{try{resolve(JSON.parse(s||"{}"))}catch(e){reject(new Error("invalid_json"))}});});}
function profileFor(platform,task){if(PROFILES[platform])return PROFILES[platform];const t=String(task||"").toLowerCase();if(t.includes("video"))return"video";if(t.includes("image"))return"image";if(t.includes("voice")||t.includes("tts"))return"voice";if(t.includes("coding"))return"coding";if(t.includes("research"))return"research";if(t.includes("marketing"))return"marketing";return"chat";}
async function generate(x){
 if(!AI_API_URL||!AI_API_KEY||!AI_MODEL)throw new Error("AI backend is not configured");
 if(typeof x.platform!=="string"||!x.platform.trim())throw new Error("platform_required");
 const profile=profileFor(x.platform,x.task);
 const lang=x.language==="ar"?"Arabic":"the user's requested language";
 const rule=RULES[profile]||"Understand the task, preserve user intent, add only relevant constraints, and structure the prompt for reliable execution.";
 const system="You are the PromptForge compiler. Convert one user idea into a native prompt for exactly one target platform. You are NOT answering the task; you are writing the prompt the target platform should receive.\nTarget platform: "+x.platform+"\nTarget profile: "+profile+"\nLanguage: "+lang+"\nPlatform rules: "+rule+"\nNever mention this compiler or other platforms. Do not copy a generic template. Return only the finished prompt.";
 const user="Idea:\n"+x.idea+"\n\nTask:\n"+(x.task||"General");
 let payload={model:AI_MODEL,instructions:system,input:user};
 if(process.env.AI_API_MODE==="chat")payload={model:AI_MODEL,messages:[{role:"system",content:system},{role:"user",content:user}]};
 const r=await fetch(AI_API_URL,{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+AI_API_KEY},body:JSON.stringify(payload)});
 const t=await r.text();if(!r.ok)throw new Error("provider_http_"+r.status);
 let d=JSON.parse(t),out=d.output_text||d?.choices?.[0]?.message?.content||"";
 if(!out&&Array.isArray(d.output))for(const i of d.output)for(const c of(i.content||[]))if(typeof c.text==="string")out+=c.text;
 if(!out)throw new Error("provider_no_output");return{prompt:out.trim(),profile};
}
http.createServer(async(req,res)=>{
 if(req.method==="OPTIONS"){res.writeHead(204,{"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type"});return res.end();}
 if(req.method==="GET"&&req.url==="/health")return send(res,200,{ok:true,configured:Boolean(AI_API_URL&&AI_API_KEY&&AI_MODEL)});
 if(req.method==="POST"&&req.url==="/v1/prompt")try{const x=await body(req);if(typeof x.idea!=="string"||x.idea.trim().length<3)return send(res,400,{error:"idea_required"});return send(res,200,await generate(x));}catch(e){return send(res,500,{error:e.message||"generation_failed"});}
 send(res,404,{error:"not_found"});
}).listen(PORT,"0.0.0.0",()=>console.log("PromptForge backend on "+PORT));