package com.promptforge.ai;
import android.app.*; import android.content.*; import com.android.billingclient.api.*; import java.util.*;
public final class BillingManager{
 public static final String MONTHLY="premium_monthly", YEARLY="premium_yearly";
 public interface Listener{void premium(boolean v);void prices(String m,String y);void msg(String s);}
 private final Storage store; private final Listener lis; private final BillingClient client; private ProductDetails m,y;
 public BillingManager(Context c,Storage s,Listener l){store=s;lis=l;client=BillingClient.newBuilder(c.getApplicationContext()).setListener((r,ps)->{if(r.getResponseCode()==BillingClient.BillingResponseCode.OK&&ps!=null)for(Purchase p:ps)handle(p);}).enablePendingPurchases(PendingPurchasesParams.newBuilder().enableOneTimeProducts().enablePrepaidPlans().build()).enableAutoServiceReconnection().build();}
 public void start(){client.startConnection(new BillingClientStateListener(){public void onBillingSetupFinished(BillingResult r){if(r.getResponseCode()==0){load();restore();}else lis.msg(r.getDebugMessage());}public void onBillingServiceDisconnected(){}});}
 private void load(){List<QueryProductDetailsParams.Product> a=new ArrayList<>();a.add(QueryProductDetailsParams.Product.newBuilder().setProductId(MONTHLY).setProductType(BillingClient.ProductType.SUBS).build());a.add(QueryProductDetailsParams.Product.newBuilder().setProductId(YEARLY).setProductType(BillingClient.ProductType.SUBS).build());client.queryProductDetailsAsync(QueryProductDetailsParams.newBuilder().setProductList(a).build(),(r,d)->{if(r.getResponseCode()==0){for(ProductDetails x:d.getProductDetailsList()){if(MONTHLY.equals(x.getProductId()))m=x;if(YEARLY.equals(x.getProductId()))y=x;}lis.prices(price(m),price(y));}});}
 private String price(ProductDetails d){if(d==null||d.getSubscriptionOfferDetails()==null||d.getSubscriptionOfferDetails().isEmpty())return"—";ProductDetails.PricingPhaseList z=d.getSubscriptionOfferDetails().get(0).getPricingPhases();return z.getPricingPhaseList().get(z.getPricingPhaseList().size()-1).getFormattedPrice();}
 private void handle(Purchase p){if(p.getPurchaseState()!=Purchase.PurchaseState.PURCHASED)return;for(String id:p.getProducts())if(MONTHLY.equals(id)||YEARLY.equals(id)){store.premium(true);lis.premium(true);if(!p.isAcknowledged())client.acknowledgePurchase(AcknowledgePurchaseParams.newBuilder().setPurchaseToken(p.getPurchaseToken()).build(),r->{});}}
 public void restore(){QueryPurchasesParams q=QueryPurchasesParams.newBuilder().setProductType(BillingClient.ProductType.SUBS).build();client.queryPurchasesAsync(q,(r,ps)->{boolean ok=false;if(r.getResponseCode()==0&&ps!=null)for(Purchase p:ps)if(p.getPurchaseState()==Purchase.PurchaseState.PURCHASED)for(String id:p.getProducts())if(MONTHLY.equals(id)||YEARLY.equals(id))ok=true;store.premium(ok);lis.premium(ok);});}
 public void buy(Activity a,boolean yearly){ProductDetails d=yearly?y:m;if(d==null){lis.msg("Play subscription is not configured yet.");return;}List<ProductDetails.SubscriptionOfferDetails> o=d.getSubscriptionOfferDetails();if(o==null||o.isEmpty()){lis.msg("No offer available.");return;}BillingFlowParams.ProductDetailsParams pd=BillingFlowParams.ProductDetailsParams.newBuilder().setProductDetails(d).setOfferToken(o.get(0).getOfferToken()).build();BillingFlowParams b=BillingFlowParams.newBuilder().setProductDetailsParamsList(Collections.singletonList(pd)).build();client.launchBillingFlow(a,b);}
}
