package com.promptforge.ai;
import android.app.*; import android.content.*; import android.graphics.*; import android.graphics.drawable.*; import android.net.Uri; import android.os.*; import android.view.*; import android.widget.*; import java.util.*;
public class MainActivity extends Activity{
 Storage s; BillingManager billing; List<Platform> ps; String lang="",sel="ChatGPT",task="General",last="",mp="—",yp="—"; int BG=Color.rgb(5,8,23),P=Color.rgb(13,24,49),P2=Color.rgb(9,18,40),B=Color.rgb(37,52,90),BL=Color.rgb(25,191,255),PU=Color.rgb(123,77,255),W=Color.rgb(246,248,255),M=Color.rgb(169,180,208);
 boolean ar(){return"ar".equals(lang);} String t(String a,String e){return ar()?a:e;} String bidi(String x){if(x==null||!ar())return x;StringBuilder o=new StringBuilder();boolean latin=false;for(int i=0;i<x.length();i++){char ch=x.charAt(i);boolean l=(ch<128)&&((ch>="A".charAt(0)&&ch<="Z".charAt(0))||(ch>="a".charAt(0)&&ch<="z".charAt(0))||(ch>="0".charAt(0)&&ch<="9")||".:/_-@+#%".indexOf(ch)>=0);if(l&&!latin)o.append("\u2066");if(!l&&latin)o.append("\u2069");o.append(ch);latin=l;}if(latin)o.append("\u2069");return o.toString();} String taskName(){if(!ar())return task;if(task.equals("General"))return"عام";if(task.equals("Marketing"))return"تسويق";if(task.equals("Image prompt"))return"برومبت صورة";if(task.equals("Video prompt"))return"برومبت فيديو";if(task.equals("Voice / TTS"))return"صوت / TTS";if(task.equals("Coding"))return"برمجة";if(task.equals("Research"))return"بحث";if(task.equals("Education"))return"تعليم";if(task.equals("Social media"))return"سوشيال ميديا";if(task.equals("Business"))return"أعمال";return task;} String taskLabel(){return t("المهمة: ","Task: ")+taskName();}
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);s=new Storage(this);ps=PlatformRepository.all();billing=new BillingManager(this,s,new BillingManager.Listener(){public void premium(boolean v){s.premium(v);}public void prices(String m,String y){mp=m;yp=y;}public void msg(String x){if(x!=null&&!x.isEmpty())toast(x);}});billing.start();lang=s.lang();if(lang.isEmpty())language();else home();}
 LinearLayout root(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(22,18,22,22);l.setBackgroundColor(BG);l.setLayoutDirection(ar()?View.LAYOUT_DIRECTION_RTL:View.LAYOUT_DIRECTION_LTR);final int pl=l.getPaddingLeft(),pt=l.getPaddingTop(),pr=l.getPaddingRight(),pb=l.getPaddingBottom();l.setOnApplyWindowInsetsListener((v,in)->{if(Build.VERSION.SDK_INT>=30){android.graphics.Insets z=in.getInsets(android.view.WindowInsets.Type.systemBars());v.setPadding(pl+z.left,pt+z.top,pr+z.right,pb+z.bottom);}else{v.setPadding(pl+in.getSystemWindowInsetLeft(),pt+in.getSystemWindowInsetTop(),pr+in.getSystemWindowInsetRight(),pb+in.getSystemWindowInsetBottom());}return in;});return l;}
 ScrollView scroll(LinearLayout x){ScrollView v=new ScrollView(this);v.setFillViewport(true);v.addView(x);return v;}
 TextView tv(String x,float z,int c,boolean bold){TextView v=new TextView(this);v.setText(bidi(x));v.setTextSize(z);v.setTextColor(c);v.setHorizontallyScrolling(false);v.setTypeface(Typeface.DEFAULT,bold?1:0);v.setPadding(0,5,0,5);v.setGravity(ar()?Gravity.RIGHT:Gravity.LEFT);return v;}
 GradientDrawable bg(int c,int st,int r){GradientDrawable d=new GradientDrawable();d.setColor(c);if(st!=0)d.setStroke(2,st);d.setCornerRadius(r);return d;}
 Button btn(String x,boolean hi){Button b=new Button(this);b.setAllCaps(false);b.setText(bidi(x));b.setTextColor(W);b.setTextSize(15);b.setGravity(Gravity.CENTER);b.setPadding(14,0,14,0);b.setMinWidth(0);b.setMinHeight(0);b.setBackgroundTintList(null);b.setStateListAnimator(null);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(hi?new GradientDrawable(GradientDrawable.Orientation.LEFT_RIGHT,new int[]{BL,PU}):bg(P2,B,28));return b;}
 void gap(LinearLayout r,int h){Space v=new Space(this);r.addView(v,new LinearLayout.LayoutParams(1,h));}
 void head(LinearLayout r,String a,String e){r.addView(tv(t(a,e),24,W,true));}
 void language(){LinearLayout r=root();r.setGravity(Gravity.CENTER_HORIZONTAL);r.addView(tv("🌐  "+t("لغة التطبيق","App language"),16,W,true));gap(r,20);r.addView(tv("⚡",64,BL,true));r.addView(tv("PromptForge AI",34,W,true));r.addView(tv("صمّم البرومبت .. ودع الـ AI يعمل الباقي",18,M,false));gap(r,25);r.addView(tv("العربية",20,W,true));Button arB=btn("العربية",true); arB.setCompoundDrawablesWithIntrinsicBounds(getDrawable(R.drawable.sy_flag),null,null,null);arB.setOnClickListener(v->{lang="ar";s.lang(lang);home();});r.addView(arB,new LinearLayout.LayoutParams(-1,64));gap(r,10);Button enB=btn("🇬🇧  English",false);enB.setOnClickListener(v->{lang="en";s.lang(lang);home();});r.addView(enB,new LinearLayout.LayoutParams(-1,64));setContentView(r);}
 void langDialog(){new AlertDialog.Builder(this).setTitle(t("لغة التطبيق","App language")).setItems(new String[]{"🇸🇾 العربية","🇬🇧 English"},(d,w)->{lang=w==0?"ar":"en";s.lang(lang);home();}).show();}
 void home(){LinearLayout r=root();FrameLayout top=new FrameLayout(this);TextView title=tv(t("مرحباً في PromptForge AI","Welcome to PromptForge AI"),19,W,true);title.setGravity(Gravity.CENTER);title.setSingleLine(true);title.setEllipsize(android.text.TextUtils.TruncateAt.END);top.addView(title,new FrameLayout.LayoutParams(-1,54));Button lb=btn(ar()?"AR":"EN",false);if(ar())lb.setCompoundDrawablesWithIntrinsicBounds(getDrawable(R.drawable.sy_flag),null,null,null);lb.setOnClickListener(v->langDialog());FrameLayout.LayoutParams lp=new FrameLayout.LayoutParams(60,50);lp.gravity=Gravity.CENTER_VERTICAL|(ar()?Gravity.LEFT:Gravity.RIGHT);top.addView(lb,lp);r.addView(top);
  TextView hero=tv(t("حوّل فكرتك إلى Prompt احترافي","Turn your idea into a powerful prompt"),20,W,true);hero.setPadding(0,12,0,8);r.addView(hero);r.addView(tv(t("يدعم عشرات منصات الذكاء الاصطناعي مع محرك قابل للتوسعة","Supports dozens of AI tools with an extensible engine"),14,M,false));
  gap(r,16);r.addView(card("✨",t("إنشاء Prompt","Create Prompt"),t("حوّل فكرتك إلى برومبت جاهز","Turn an idea into a ready prompt"),v->create()),new LinearLayout.LayoutParams(-1,100));gap(r,10);r.addView(card("🛠️",t("تحسين Prompt","Improve Prompt"),t("طوّر أي Prompt موجود","Upgrade any existing prompt"),v->improve()),new LinearLayout.LayoutParams(-1,100));gap(r,10);
  r.addView(card("🌐",t("كل المنصات","All AI Platforms"),ar()?ps.size()+" منصة وأداة":ps.size()+" tools and platforms",v->platforms()),new LinearLayout.LayoutParams(-1,100));gap(r,10);r.addView(card("⭐",t("المحفوظات","Saved"),t("البرومبتات التي حفظتها","Your saved prompts"),v->listScreen("saved")),new LinearLayout.LayoutParams(-1,100));gap(r,10);r.addView(card("🕘",t("السجل","History"),t("آخر البرومبتات","Latest generated prompts"),v->listScreen("history")),new LinearLayout.LayoutParams(-1,100));gap(r,10);r.addView(card("👑",t("Premium","Premium"),t("افتح كل المزايا","Unlock the full experience"),v->premium()),new LinearLayout.LayoutParams(-1,100));gap(r,10);Button st=btn("⚙️  "+t("الإعدادات","Settings"),false);st.setOnClickListener(v->settings());r.addView(st,new LinearLayout.LayoutParams(-1,58));setContentView(scroll(r));}
 View card(String icon,String title,String desc,View.OnClickListener c){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.HORIZONTAL);x.setGravity(Gravity.CENTER_VERTICAL);x.setPadding(18,8,18,8);x.setBackground(bg(P,B,26));x.setOnClickListener(c);TextView i=tv(icon,30,BL,true);i.setGravity(Gravity.CENTER);x.addView(i,new LinearLayout.LayoutParams(64,70));LinearLayout q=new LinearLayout(this);q.setOrientation(LinearLayout.VERTICAL);q.addView(tv(title,17,W,true));q.addView(tv(desc,13,M,false));x.addView(q,new LinearLayout.LayoutParams(0,-2,1));return x;}
 void create(){LinearLayout r=root();head(r,"إنشاء Prompt","Create Prompt");EditText e=new EditText(this);e.setTextColor(W);e.setHintTextColor(M);e.setHint(t("اكتب فكرتك هنا...","Describe your idea..."));e.setGravity(Gravity.TOP|Gravity.START);e.setMinLines(7);e.setPadding(16,14,16,14);e.setBackground(bg(P2,B,24));r.addView(e,new LinearLayout.LayoutParams(-1,190));gap(r,10);Button choose=btn(t("المنصة: ","Platform: ")+sel,true);choose.setOnClickListener(v->platforms());r.addView(choose,new LinearLayout.LayoutParams(-1,58));gap(r,8);Button taskBtn=btn(taskLabel(),true);taskBtn.setOnClickListener(v->taskDialog(taskBtn));r.addView(taskBtn,new LinearLayout.LayoutParams(-1,58));gap(r,8);Button gen=btn(t("✦  توليد Prompt","✦  Generate Prompt"),true);gen.setOnClickListener(v->generate(e.getText().toString()));r.addView(gen,new LinearLayout.LayoutParams(-1,62));r.addView(tv(t("اليوم متاح: ","Today remaining: ")+s.remaining(),13,M,false));setContentView(scroll(r));}
 void taskDialog(Button target){String[] en={"General","Marketing","Image prompt","Video prompt","Voice / TTS","Coding","Research","Education","Social media","Business"};String[] arx={"عام","تسويق","برومبت صورة","برومبت فيديو","صوت / TTS","برمجة","بحث","تعليم","سوشيال ميديا","أعمال"};String[] show=ar()?arx:en;new AlertDialog.Builder(this).setTitle(t("اختر نوع المهمة","Choose task")).setItems(show,(d,w)->{task=en[w];target.setText(t("المهمة: ","Task: ")+taskName());}).show();}
 void generate(String idea){if(!s.consume()){toast(t("وصلت للحد المجاني اليومي. افتح Premium.","Daily free limit reached. Upgrade to Premium."));premium();return;}String base=s.get("backend_url","").trim();if(!base.isEmpty()){toast(t("جار التوليد...","Generating..."));new RemotePromptClient().generate(base,idea,sel,task,lang,(ok,val)->runOnUiThread(()->{if(ok){last=val;s.add("history",val);result();}else{local(idea);}}));}else local(idea);}
 void local(String idea){last=PromptEngine.generate(idea,find(sel),task,ar());s.add("history",last);result();}
 void result(){LinearLayout r=root();head(r,"النتيجة","Result");TextView v=tv(last,15,W,false);v.setPadding(16,16,16,16);v.setBackground(bg(P,B,24));r.addView(v);gap(r,10);Button cp=btn(t("نسخ","Copy"),true);cp.setOnClickListener(x->copy(last));r.addView(cp,new LinearLayout.LayoutParams(-1,58));gap(r,8);Button sv=btn("⭐ "+t("حفظ","Save"),false);sv.setOnClickListener(x->{s.add("saved",last);toast(t("تم الحفظ","Saved"));});r.addView(sv,new LinearLayout.LayoutParams(-1,58));gap(r,8);Button sh=btn(t("مشاركة","Share"),false);sh.setOnClickListener(x->{Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,last);startActivity(Intent.createChooser(i,t("مشاركة","Share")));});r.addView(sh,new LinearLayout.LayoutParams(-1,58));setContentView(scroll(r));}
 void improve(){LinearLayout r=root();head(r,"تحسين Prompt","Improve Prompt");EditText e=new EditText(this);e.setTextColor(W);e.setHintTextColor(M);e.setHint(t("ألصق البرومبت هنا...","Paste your prompt..."));e.setGravity(Gravity.TOP|Gravity.START);e.setMinLines(8);e.setBackground(bg(P2,B,24));r.addView(e,new LinearLayout.LayoutParams(-1,210));gap(r,10);Button b=btn(t("✨ تحسين","✨ Improve"),true);b.setOnClickListener(v->{last=PromptEngine.improve(e.getText().toString(),ar());s.add("history",last);result();});r.addView(b,new LinearLayout.LayoutParams(-1,62));setContentView(scroll(r));}
 void platforms(){LinearLayout r=root();head(r,"منصات AI","AI Platforms");EditText q=new EditText(this);q.setHint(t("بحث...","Search..."));q.setTextColor(W);q.setHintTextColor(M);q.setSingleLine(true);q.setBackground(bg(P2,B,22));r.addView(q,new LinearLayout.LayoutParams(-1,56));LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);r.addView(box);Runnable fill=()->{box.removeAllViews();String s0=q.getText().toString().toLowerCase(Locale.ROOT);for(Platform p:ps)if(s0.isEmpty()||p.name.toLowerCase(Locale.ROOT).contains(s0)||p.category.toLowerCase(Locale.ROOT).contains(s0)){Button b=btn(p.name+"  •  "+p.category,false);b.setOnClickListener(v->{sel=p.name;showWeb(p);});box.addView(b,new LinearLayout.LayoutParams(-1,58));gap(box,6);}};q.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){fill.run();}public void afterTextChanged(android.text.Editable e){}});fill.run();setContentView(scroll(r));}
 Platform find(String n){for(Platform p:ps)if(p.name.equals(n))return p;return ps.get(0);}
 void showWeb(Platform p){new AlertDialog.Builder(this).setTitle(p.name).setMessage(p.category).setPositiveButton(t("استخدام","Use"),(d,w)->create()).setNegativeButton(t("فتح المنصة","Open"),(d,w)->open(p.url)).show();}
 void listScreen(String k){LinearLayout r=root();head(r,k.equals("saved")?"المحفوظات":"السجل",k.equals("saved")?"Saved":"History");List<String>a=s.list(k);if(a.isEmpty())r.addView(tv(t("لا يوجد شيء بعد","Nothing yet"),17,M,false));for(String x:a){TextView z=tv(x,14,W,false);z.setPadding(14,14,14,14);z.setBackground(bg(P,B,22));r.addView(z,new LinearLayout.LayoutParams(-1,180));gap(r,8);}setContentView(scroll(r));}
 void settings(){LinearLayout r=root();head(r,"الإعدادات","Settings");Button l=btn(ar()?"🇸🇾 العربية":"🇬🇧 English",false);l.setOnClickListener(v->langDialog());r.addView(l,new LinearLayout.LayoutParams(-1,58));gap(r,12);r.addView(tv(t("Backend URL (اختياري)","Backend URL (optional)"),16,W,true));EditText u=new EditText(this);u.setText(s.get("backend_url",""));u.setHint("https://...");u.setTextColor(W);u.setHintTextColor(M);u.setSingleLine(true);u.setBackground(bg(P2,B,22));r.addView(u,new LinearLayout.LayoutParams(-1,56));gap(r,8);Button save=btn(t("حفظ","Save"),true);save.setOnClickListener(v->{s.put("backend_url",u.getText().toString().trim());toast(t("تم الحفظ","Saved"));});r.addView(save,new LinearLayout.LayoutParams(-1,58));gap(r,8);Button test=btn(t("اختبار الاتصال","Test connection"),false);test.setOnClickListener(v->new RemotePromptClient().health(u.getText().toString().trim(),(ok,msg)->runOnUiThread(()->toast(ok?t("الخادم يعمل ✅","Backend healthy ✅"):t("فشل الاتصال","Connection failed")))));r.addView(test,new LinearLayout.LayoutParams(-1,58));gap(r,12);Button pm=btn("👑 Premium",true);pm.setOnClickListener(v->premium());r.addView(pm,new LinearLayout.LayoutParams(-1,58));setContentView(scroll(r));}
 void premium(){LinearLayout r=root();head(r,"Premium","Premium");r.addView(tv(t("توليد AI حقيقي، حدود أعلى، قوالب ومزايا إضافية.","Real AI generation, higher limits, templates and more."),16,W,false));gap(r,12);Button m=btn("⭐ "+t("شهري","Monthly")+"  "+mp,true);m.setOnClickListener(v->billing.buy(this,false));r.addView(m,new LinearLayout.LayoutParams(-1,62));gap(r,8);Button y=btn("👑 "+t("سنوي","Yearly")+"  "+yp,false);y.setOnClickListener(v->billing.buy(this,true));r.addView(y,new LinearLayout.LayoutParams(-1,62));gap(r,8);Button re=btn(t("استعادة الاشتراك","Restore subscription"),false);re.setOnClickListener(v->billing.restore());r.addView(re,new LinearLayout.LayoutParams(-1,58));setContentView(scroll(r));}
 void open(String u){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(u)));}catch(Exception e){toast("Cannot open URL");}}
 void copy(String x){((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("PromptForge",x));toast(t("تم النسخ","Copied"));}
 void toast(String x){Toast.makeText(this,x,Toast.LENGTH_SHORT).show();}
}
