package com.promptforge.ai;
import java.util.*;
public final class PlatformRepository{
 private PlatformRepository(){}
 public static List<Platform> all(){
  List<Platform> p=new ArrayList<>();
  add(p,"ChatGPT","Chat","https://chatgpt.com","general"); add(p,"Claude","Chat","https://claude.ai","general"); add(p,"Gemini","Chat","https://gemini.google.com","general"); add(p,"Grok","Chat","https://grok.com","general"); add(p,"Perplexity","Research","https://perplexity.ai","research"); add(p,"Copilot","Chat","https://copilot.microsoft.com","general"); add(p,"Meta AI","Chat","https://meta.ai","general"); add(p,"DeepSeek","Coding","https://chat.deepseek.com","coding"); add(p,"Le Chat","Chat","https://chat.mistral.ai","general"); add(p,"Poe","AI Hub","https://poe.com","general"); add(p,"NotebookLM","Research","https://notebooklm.google.com","research");
  add(p,"Midjourney","Image","https://midjourney.com","image"); add(p,"Adobe Firefly","Image","https://firefly.adobe.com","image"); add(p,"Ideogram","Image","https://ideogram.ai","image"); add(p,"Leonardo AI","Image","https://leonardo.ai","image"); add(p,"FLUX","Image","https://bfl.ai","image"); add(p,"Stable Diffusion","Image","https://stability.ai","image"); add(p,"Recraft","Image","https://recraft.ai","image"); add(p,"Krea","Image","https://krea.ai","image"); add(p,"Canva AI","Design","https://canva.com/ai","image"); add(p,"Freepik AI","Image","https://freepik.com/ai","image"); add(p,"Magnific","Image","https://magnific.ai","image");
  add(p,"Runway","Video","https://runwayml.com","video"); add(p,"Google Veo","Video","https://deepmind.google/models/veo/","video"); add(p,"Kling AI","Video","https://klingai.com","video"); add(p,"Pika","Video","https://pika.art","video"); add(p,"Luma Dream Machine","Video","https://lumalabs.ai/dream-machine","video"); add(p,"Hailuo AI","Video","https://hailuoai.video","video"); add(p,"PixVerse","Video","https://pixverse.ai","video"); add(p,"Haiper","Video","https://haiper.ai","video"); add(p,"Vidu","Video","https://vidu.com","video"); add(p,"LTX Studio","Video","https://ltx.studio","video");
  add(p,"ElevenLabs","Voice","https://elevenlabs.io","voice"); add(p,"PlayHT","Voice","https://play.ht","voice"); add(p,"Cartesia","Voice","https://cartesia.ai","voice"); add(p,"Fish Audio","Voice","https://fish.audio","voice"); add(p,"Murf","Voice","https://murf.ai","voice"); add(p,"Speechify","Voice","https://speechify.com","voice"); add(p,"Suno","Music","https://suno.com","music"); add(p,"Udio","Music","https://udio.com","music"); add(p,"Stable Audio","Music","https://stableaudio.com","music");
  add(p,"Cursor","Coding","https://cursor.com","coding"); add(p,"GitHub Copilot","Coding","https://github.com/features/copilot","coding"); add(p,"Claude Code","Coding","https://anthropic.com/claude-code","coding"); add(p,"Windsurf","Coding","https://windsurf.com","coding"); add(p,"Replit","Coding","https://replit.com","coding"); add(p,"Amazon Q Developer","Coding","https://aws.amazon.com/q/developer/","coding"); add(p,"Gemini Code Assist","Coding","https://codeassist.google","coding"); add(p,"Tabnine","Coding","https://tabnine.com","coding");
  add(p,"Jasper","Marketing","https://jasper.ai","marketing"); add(p,"Copy.ai","Marketing","https://copy.ai","marketing"); add(p,"Writesonic","Marketing","https://writesonic.com","marketing"); add(p,"Grammarly","Writing","https://grammarly.com","writing"); add(p,"Writer","Writing","https://writer.com","writing"); add(p,"Notion AI","Productivity","https://notion.com/product/ai","productivity"); add(p,"Gamma","Presentations","https://gamma.app","presentations"); add(p,"Beautiful.ai","Presentations","https://beautiful.ai","presentations"); add(p,"Tome","Presentations","https://tome.app","presentations"); add(p,"Napkin AI","Presentations","https://napkin.ai","presentations"); add(p,"Framer AI","Design","https://framer.com/ai","design"); add(p,"Canva Magic Studio","Design","https://canva.com/magic-studio","design");
  add(p,"Elicit","Research","https://elicit.com","research"); add(p,"Consensus","Research","https://consensus.app","research"); add(p,"SciSpace","Research","https://scispace.com","research"); add(p,"Meshy","3D","https://meshy.ai","3d"); add(p,"Tripo AI","3D","https://tripo3d.ai","3d"); add(p,"Hugging Face","AI Hub","https://huggingface.co","general"); add(p,"Replicate","AI API","https://replicate.com","general"); add(p,"OpenRouter","AI Hub","https://openrouter.ai","general"); add(p,"Together AI","AI API","https://together.ai","general"); add(p,"Fireworks AI","AI API","https://fireworks.ai","general"); add(p,"Fal.ai","AI API","https://fal.ai","general");
  add(p,"Photoroom","Design","https://photoroom.com","design"); add(p,"Looka","Design","https://looka.com","design"); add(p,"Descript","Video","https://descript.com","video"); add(p,"OpusClip","Video","https://opus.pro","video"); add(p,"Otter.ai","Productivity","https://otter.ai","productivity"); add(p,"Fireflies.ai","Productivity","https://fireflies.ai","productivity"); add(p,"Mem","Productivity","https://mem.ai","productivity"); add(p,"You.com","Research","https://you.com","research"); add(p,"Character.AI","Chat","https://character.ai","general"); add(p,"Pi","Chat","https://pi.ai","general");
  return Collections.unmodifiableList(p);
 }
 private static void add(List<Platform> p,String n,String c,String u,String s){p.add(new Platform(n,c,u,s));}
}
