package com.promptforge.ai;
import java.io.*; import java.net.*; import java.nio.charset.StandardCharsets; import org.json.*;
public final class RemotePromptClient{
 public interface CB{void done(boolean ok,String value);}
 private void post(String url,String body,CB cb){
  new Thread(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setRequestMethod("POST");c.setConnectTimeout(10000);c.setReadTimeout(30000);c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");c.getOutputStream().write(body.getBytes(StandardCharsets.UTF_8));int code=c.getResponseCode();InputStream in=code>=200&&code<300?c.getInputStream():c.getErrorStream();java.io.BufferedReader br=new java.io.BufferedReader(new java.io.InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder sb=new StringBuilder();String line;while((line=br.readLine())!=null){sb.append(line).append("\n");}String s=sb.toString();cb.done(code>=200&&code<300,s);}catch(Exception e){cb.done(false,e.getMessage()==null?"network error":e.getMessage());}}).start();
 }
 private void postAuth(String url,String token,String body,CB cb){new Thread(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setRequestMethod("PATCH");c.setConnectTimeout(10000);c.setReadTimeout(15000);c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");c.setRequestProperty("Authorization","Bearer "+token);c.getOutputStream().write(body.getBytes(StandardCharsets.UTF_8));int code=c.getResponseCode();InputStream in=code>=200&&code<300?c.getInputStream():c.getErrorStream();BufferedReader br=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder sb=new StringBuilder();String line;while((line=br.readLine())!=null)sb.append(line).append("\n");cb.done(code>=200&&code<300,sb.toString());}catch(Exception e){cb.done(false,e.getMessage()==null?"network error":e.getMessage());}}).start();}
 public void updatePassword(String base,String token,String password,CB cb){try{JSONObject j=new JSONObject();j.put("password",password);postAuth(base.replaceAll("/$","")+"/v1/auth/account",token,j.toString(),cb);}catch(Exception e){cb.done(false,e.getMessage());}}
 public void health(String base,CB cb){new Thread(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(base.replaceAll("/$","")+"/health").openConnection();c.setConnectTimeout(8000);c.setReadTimeout(8000);int code=c.getResponseCode();cb.done(code==200,""+code);}catch(Exception e){cb.done(false,e.getMessage());}}).start();}
 public void login(String base,String username,String password,CB cb){try{JSONObject j=new JSONObject();j.put("username",username);j.put("password",password);post(base.replaceAll("/$","")+"/v1/auth/login",j.toString(),cb);}catch(Exception e){cb.done(false,e.getMessage());}} public void adminLogin(String base,String username,String password,CB cb){try{JSONObject j=new JSONObject();j.put("username",username);j.put("password",password);post(base.replaceAll("/$","")+"/admin/login",j.toString(),cb);}catch(Exception e){cb.done(false,e.getMessage());}} public void generate(String base,String idea,String platform,String task,String lang,String token,CB cb){try{JSONObject j=new JSONObject();j.put("idea",idea);j.put("platform",platform);j.put("task",task);j.put("language",lang);if(token!=null&&!token.isEmpty())j.put("token",token);post(base.replaceAll("/$","")+"/v1/prompt",j.toString(),(ok,s)->{if(!ok){cb.done(false,s);return;}try{cb.done(true,new JSONObject(s).optString("prompt",s));}catch(Exception e){cb.done(true,s);}});}catch(Exception e){cb.done(false,e.getMessage());}}
}
