package com.promptforge.ai;
import java.io.*; import java.net.*; import java.nio.charset.StandardCharsets; import org.json.*;
public final class RemotePromptClient{
 public interface CB{void done(boolean ok,String value);}
 private static String safeBody(HttpURLConnection c){
  try{InputStream in=c.getResponseCode()>=200&&c.getResponseCode()<300?c.getInputStream():c.getErrorStream();if(in==null)return "";BufferedReader br=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder sb=new StringBuilder();String line;while((line=br.readLine())!=null)sb.append(line).append("\n");return sb.toString();}catch(Exception e){return "";}
 }
 private void post(String url,String body,CB cb){
  new Thread(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setRequestMethod("POST");c.setConnectTimeout(10000);c.setReadTimeout(30000);c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");c.getOutputStream().write(body.getBytes(StandardCharsets.UTF_8));int code=c.getResponseCode();String s=safeBody(c);if(code>=200&&code<300){cb.done(true,s);}else{cb.done(false,parseError(s,code));}}catch(Exception e){cb.done(false,e.getMessage()==null?"network error":e.getMessage());}}).start();
 }
 private void postAuth(String url,String token,String body,CB cb){new Thread(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setRequestMethod("PATCH");c.setConnectTimeout(10000);c.setReadTimeout(15000);c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");c.setRequestProperty("Authorization","Bearer "+token);c.getOutputStream().write(body.getBytes(StandardCharsets.UTF_8));int code=c.getResponseCode();String s=safeBody(c);if(code>=200&&code<300){cb.done(true,s);}else{cb.done(false,parseError(s,code));}}catch(Exception e){cb.done(false,e.getMessage()==null?"network error":e.getMessage());}}).start();}
 private static String parseError(String response,int code){
  if(response==null||response.trim().isEmpty())return "request_failed_"+code;
  try{JSONObject j=new JSONObject(response);if(j.has("error")){JSONObject e=j.optJSONObject("error");if(e!=null){String msg=e.optString("message",e.optString("error","request_failed_"+code));if(!msg.isEmpty())return msg;}String msg=j.optString("error","request_failed_"+code);if(!msg.isEmpty())return msg;}}catch(Exception ignored){}
  return response.trim();
 }
 public void updatePassword(String base,String token,String password,CB cb){try{JSONObject j=new JSONObject();j.put("password",password);postAuth(base.replaceAll("/$","")+"/v1/auth/account",token,j.toString(),cb);}catch(Exception e){cb.done(false,e.getMessage());}}
 public void health(String base,CB cb){new Thread(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(base.replaceAll("/$","")+"/health/ai").openConnection();c.setConnectTimeout(8000);c.setReadTimeout(8000);int code=c.getResponseCode();String body=safeBody(c);boolean ok=code==200;if(ok){try{JSONObject status=new JSONObject(body);if(status.has("configured"))ok=status.optBoolean("configured",false);}catch(Exception ignored){}}cb.done(ok,body.isEmpty()?""+code:body);}catch(Exception e){cb.done(false,e.getMessage()==null?"network error":e.getMessage());}}).start();}
 public void login(String base,String username,String password,CB cb){try{JSONObject j=new JSONObject();j.put("username",username);j.put("password",password);post(base.replaceAll("/$","")+"/v1/auth/login",j.toString(),cb);}catch(Exception e){cb.done(false,e.getMessage());}} public void adminLogin(String base,String username,String password,CB cb){try{JSONObject j=new JSONObject();j.put("username",username);j.put("password",password);post(base.replaceAll("/$","")+"/admin/login",j.toString(),cb);}catch(Exception e){cb.done(false,e.getMessage());}} public void generate(String base,String idea,String platform,String task,String token,CB cb){try{JSONObject j=new JSONObject();j.put("idea",idea);j.put("platform",platform);j.put("task",task);if(token!=null&&!token.isEmpty())j.put("token",token);post(base.replaceAll("/$","")+"/v1/prompt",j.toString(),(ok,s)->{if(!ok){cb.done(false,s);return;}try{JSONObject obj=new JSONObject(s);if(obj.has("error")){cb.done(false,obj.optString("error","generation_failed"));return;}cb.done(true,obj.optString("prompt",s));}catch(Exception e){cb.done(false,"invalid_server_response");}});}catch(Exception e){cb.done(false,e.getMessage());}}
}
